# Generated by Django 2.0.13 on 2019-11-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctrine',
            options={'default_permissions': (('manage', 'Can manage doctrines and fits.'),)},
        ),
        migrations.AlterModelOptions(
            name='dogmaattribute',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='dogmaeffect',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='fitting',
            options={'default_permissions': (('access_fittings', 'Can access the fittings module.'),)},
        ),
        migrations.AlterModelOptions(
            name='fittingitem',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'default_permissions': ()},
        ),
        migrations.AlterUniqueTogether(
            name='fitting',
            unique_together={('ship_type_type_id', 'name')},
        ),
    ]
