# Generated by Django 2.2.4 on 2019-12-01 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fittings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctrine',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
