# Generated by Django 2.2.12 on 2020-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittings', '0003_remove_type_description_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
    ]
